/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.table.DefaultTableModel;
import controller.ChangeController;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ChildModel;
/**
 *
 * @author Microsoft Windows
 */
public class Change extends javax.swing.JPanel {
    DefaultTableModel model;
    ChangeController controller;
    ArrayList<ChildModel> list;
    /** Creates new form Home */
    public Change() throws SQLException, ClassNotFoundException {
        initComponents();
        model = (DefaultTableModel) ChangeTb.getModel();
        model.setColumnIdentifiers(new Object[]{"STT","ID","Tên trẻ","Ngày sinh","Giới tính","Phụ huynh","Địa chỉ","Trường","Lớp","Học lực","Quà dịp này"});
        list = new ChangeController().getList();
        controller = new ChangeController();
        controller.CreatAll(list, model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChangeTb = new javax.swing.JTable();
        BtnChg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDoB = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtAddrs = new javax.swing.JTextField();
        txtPrs = new javax.swing.JTextField();
        txtSchool = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CbGen = new javax.swing.JComboBox<>();
        CbRate = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CHỌN THÔNG TIN CẦN THAY ĐỔI");

        ChangeTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ChangeTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ChangeTb);

        BtnChg.setText("Thay đổi");
        BtnChg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChgActionPerformed(evt);
            }
        });

        jLabel2.setText("Họ và tên:");

        jLabel3.setText("Ngày sinh:");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Phụ huynh:");

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Trường:");

        jLabel8.setText("ID:");

        txtDoB.setText("DD/MM/YYYY");

        jLabel9.setText("Lớp:");

        jLabel10.setText("Học lực:");

        CbGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nam", "nữ" }));

        CbRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "giỏi", "khá", "trung bình", "yếu" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(BtnChg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddrs, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel3)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(65, 65, 65)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtClass, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(txtPrs, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(CbGen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CbRate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(BtnChg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(CbRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnChgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChgActionPerformed
        // TODO add your handling code here:
        int  change = ChangeTb.getSelectedRow();
        if (change == -1) 
        { JOptionPane.showMessageDialog(null,"Chọn 1 dòng để nhấn");}
         else {
            if(txtcheck()){
            ChildModel t = new ChildModel();
            t.setID(Integer.parseInt(txtID.getText()));
            t.setTenTre(txtName.getText());
            try{
                t.setNgaySinh(new SimpleDateFormat("dd/MM/yyyy").parse(txtDoB.getText()));
            }
            catch(ParseException ex){
            }
            t.setTenChuHo(txtPrs.getText());
            t.setGioiTinh((String) CbGen.getSelectedItem());
            t.setDiaChi(txtAddrs.getText());
            t.setTruong(txtSchool.getText());
            t.setLop(txtClass.getText());
            t.setThanhTich((String) CbRate.getSelectedItem());
            if(t.getThanhTich().equals("Giỏi")){
                t.setSoLuongQua(8);
            }
            else if(t.getThanhTich().equals("Khá")){
                t.setSoLuongQua(5);
            }
            try {
                if (controller.changeChild(t)) {
                    JOptionPane.showMessageDialog(null, "Thay đổi  thành công!!");                    
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
        }       
    }//GEN-LAST:event_BtnChgActionPerformed

    private void ChangeTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeTbMouseClicked
        // TODO add your handling code here:
        int i = ChangeTb.getSelectedRow();
        if (list.isEmpty()){
           JOptionPane.showMessageDialog(null,"Danh sách trống"); 
        }else{
        txtName.setText(list.get(i).getTenTre());
        txtDoB.setText((String) new SimpleDateFormat("dd/MM/yy").format(list.get(i).getNgaySinh()));
        txtAddrs.setText(list.get(i).getDiaChi());
        txtPrs.setText(list.get(i).getTenChuHo());
        txtSchool.setText(list.get(i).getTruong());
        txtClass.setText(list.get(i).getLop());
        txtID.setText(Integer.toString(list.get(i).getID()));
        CbGen.setSelectedItem(list.get(i).getGioiTinh());
        CbRate.setSelectedItem(list.get(i).getThanhTich());}
    }//GEN-LAST:event_ChangeTbMouseClicked
private boolean txtcheck(){
        if(txtName.getText().trim().isEmpty()
                ||txtDoB.getText().trim().isEmpty()
                ||txtAddrs.getText().trim().isEmpty()
                ||txtPrs.getText().trim().isEmpty()
                ||txtSchool.getText().trim().isEmpty()
                ||txtClass.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập hết các thông tin bắt buộc", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
                int d = Integer.parseInt(txtID.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Số ID không thể chứa các ký tự", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        try {
                Date d = new SimpleDateFormat("dd/MM/yyyy").parse(txtDoB.getText());
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Hãy nhập đúng theo cấu trúc DD//MM/YYYY", "Warning", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnChg;
    private javax.swing.JComboBox<String> CbGen;
    private javax.swing.JComboBox<String> CbRate;
    private javax.swing.JTable ChangeTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAddrs;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtDoB;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrs;
    private javax.swing.JTextField txtSchool;
    // End of variables declaration//GEN-END:variables

}
