/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.SttController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChildModel;
import javax.swing.JTable;
/**
 *
 * @author Microsoft Windows
 */
public class Stt extends javax.swing.JPanel {
DefaultTableModel model;
ArrayList<ChildModel> list;
SttController controller;
    /** Creates new form Home */
    public Stt() throws SQLException, ClassNotFoundException {
        initComponents();
        model = (DefaultTableModel) SttTb.getModel();
        model.setColumnIdentifiers(new Object[]{"STT","Id","Tên trẻ","Ngày sinh","Giới tính","Phụ huynh","Địa chỉ","Trường","Lớp","Học lực","Trạng thái"});
        SttTb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        SttTb.getColumnModel().getColumn(0).setPreferredWidth(40);
        SttTb.getColumnModel().getColumn(1).setPreferredWidth(40);
        SttTb.getColumnModel().getColumn(2).setPreferredWidth(100);
        SttTb.getColumnModel().getColumn(5).setPreferredWidth(130);
        SttTb.getColumnModel().getColumn(6).setPreferredWidth(300);
        SttTb.getColumnModel().getColumn(7).setPreferredWidth(105);
        SttTb.getColumnModel().getColumn(8).setPreferredWidth(40);
        list = new SttController().getList();
        controller = new SttController();
        controller.CreatAll(list, model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SttTb = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("DANH SÁCH QUÀ TẶNG:");

        SttTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        SttTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SttTbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SttTbMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SttTbMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(SttTb);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chưa tặng", "Đã tặng" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    try {
        // TODO add your handling code here:
        list = new SttController().getList();
    } catch (SQLException ex) {
        Logger.getLogger(Stt.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Stt.class.getName()).log(Level.SEVERE, null, ex);
    }
        controller = new SttController();
        if(jComboBox1.getSelectedItem().equals("Tất cả")){
            controller.CreatAll(list, model);
        }
        else if(jComboBox1.getSelectedItem().equals("Chưa tặng")){
            controller.CreatUnGift(list, model);
        }
        else {
            controller.CreatGift(list, model);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void SttTbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SttTbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SttTbMousePressed

    private void SttTbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SttTbMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SttTbMouseEntered

    private void SttTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SttTbMouseClicked
        // TODO add your handling code here:
        int  change = SttTb.getSelectedRow();
        if (change == -1) 
        { JOptionPane.showMessageDialog(null,"Chọn 1 dòng để nhấn");}
         else if (JOptionPane.showConfirmDialog(null, "Bạn có chắc thay đổi trạng thái tặng quà ?","Comfirm",JOptionPane.YES_NO_OPTION) == 0) {
             controller = new SttController();
            try {
                if (controller.changeChild(list.get(change).getID(),list.get(change),list.get(change).isDaNhanQua())) {
                    JOptionPane.showMessageDialog(null, "Thay đổi thành công!!");                    
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra. Vui long kiểm tra lại!!", "Warning", JOptionPane.WARNING_MESSAGE);
            } 
            try {
                list = new SttController().getList();
            } catch (SQLException ex) {
                Logger.getLogger(Stt.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Stt.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jComboBox1.getSelectedItem().equals("Tất cả")){
                controller.CreatAll(list, model);
            }
            else if(jComboBox1.getSelectedItem().equals("Chưa tặng")){
            controller.CreatUnGift(list, model);
            }
            else {
            controller.CreatGift(list, model);
            }
        }
    }//GEN-LAST:event_SttTbMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SttTb;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
